backend:
  name: github
  repo: DusanCV/antikorupcija # zamijeni sa svojim GitHub repo imenom
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Postovi"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Tijelo", name: "body", widget: "markdown" }
